# Generated by Django 4.0.4 on 2022-04-19 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoopTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Coop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coop_name', models.CharField(max_length=200)),
                ('management_fee', models.IntegerField(null=True)),
                ('coop_tag', models.ManyToManyField(related_name='Coop', to='coopcreator.cooptag')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
