# Generated by Django 4.0.4 on 2022-04-19 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopcreator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operational_Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cooptag',
            name='description',
        ),
        migrations.AddField(
            model_name='coop',
            name='Address_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coop',
            name='Address_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coop',
            name='coop_description',
            field=models.TextField(default='Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooptag',
            name='tag_description',
            field=models.TextField(default='Text', null=True),
        ),
        migrations.AddField(
            model_name='coop',
            name='City',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Coop', to='coopcreator.operational_cities'),
        ),
    ]
