# Generated by Django 4.0.4 on 2022-04-19 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coopcreator', '0003_rename_operational_cities_operational_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coop',
            old_name='Address_1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='coop',
            old_name='Address_2',
            new_name='address_2',
        ),
        migrations.RenameField(
            model_name='coop',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='cooptag',
            old_name='tag',
            new_name='tag_name',
        ),
        migrations.RenameField(
            model_name='operational_city',
            old_name='cityName',
            new_name='city_name',
        ),
        migrations.AddField(
            model_name='coop',
            name='bring_your_own_bag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coop',
            name='coop_members',
            field=models.ManyToManyField(related_name='joined_coop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_coop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cooptag',
            name='tag_description',
            field=models.TextField(blank=True, default='Text'),
        ),
    ]
