# Generated by Django 4.0.4 on 2022-04-19 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopcreator', '0004_rename_address_1_coop_address_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseFrequencyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=100)),
                ('length_days', models.IntegerField(null=True)),
                ('opition_description', models.TextField(blank=True, default='Text')),
            ],
        ),
        migrations.RenameModel(
            old_name='Operational_City',
            new_name='OperationalCity',
        ),
        migrations.AddField(
            model_name='coop',
            name='purchase_frequency_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coop', to='coopcreator.purchasefrequencyoption'),
        ),
    ]
