# Generated by Django 4.0.4 on 2022-04-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopcreator', '0005_purchasefrequencyoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coop',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coop', to='coopcreator.operationalcity'),
        ),
        migrations.AlterField(
            model_name='coop',
            name='coop_tag',
            field=models.ManyToManyField(related_name='coop', to='coopcreator.cooptag'),
        ),
    ]
