# Generated by Django 4.0.4 on 2022-04-24 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coopcreator', '0007_coop_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coop',
            name='coop_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coop',
            name='coop_members',
            field=models.ManyToManyField(null=True, related_name='joined_coop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coop',
            name='coop_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coop',
            name='coop_tag',
            field=models.ManyToManyField(null=True, related_name='coop', to='coopcreator.cooptag'),
        ),
        migrations.AlterField(
            model_name='coop',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_coop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coop',
            name='postcode',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
