# Generated by Django 4.0.4 on 2022-04-20 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopcreator', '0007_coop_postcode'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='coopcreator.operationalcity'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postcode',
            field=models.CharField(default='text', max_length=9),
            preserve_default=False,
        ),
    ]
