# Generated by Django 4.0.4 on 2022-04-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_customuser_address_1_customuser_address_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='postcode',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
