# Generated by Django 4.0.4 on 2022-04-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_customuser_household_size_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='household_size',
            field=models.IntegerField(null=True),
        ),
    ]
