# Generated by Django 4.0.4 on 2022-04-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0006_alter_customuser_household_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='household_size',
        ),
    ]
