# Generated by Django 4.0.4 on 2022-04-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0007_remove_customuser_household_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='household_size',
            field=models.IntegerField(null=True),
        ),
    ]
