# Generated by Django 4.0.4 on 2022-04-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0009_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tocpp',
            field=models.BooleanField(null=True),
        ),
    ]
