# Generated by Django 4.0.4 on 2022-04-19 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coopcreator', '0006_alter_coop_city_alter_coop_coop_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_description', models.TextField()),
                ('minimum_purchase_amount', models.IntegerField()),
                ('item_url', models.CharField(max_length=300)),
                ('coop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coop', to='coopcreator.coop')),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuantityUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_unit_full', models.CharField(max_length=100)),
                ('quantity_unit_shorthand', models.CharField(max_length=100)),
                ('quantity_unit_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_list_coop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to='coopcreator.coop')),
                ('shopping_list_items', models.ManyToManyField(related_name='shopping_list', to='coopmanager.coopitem')),
            ],
        ),
        migrations.CreateModel(
            name='PriceBrackets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('quantity_price', models.IntegerField()),
                ('coop_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_brackets', to='coopmanager.coopitem')),
            ],
        ),
        migrations.AddField(
            model_name='coopitem',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='coopmanager.itemtype'),
        ),
        migrations.AddField(
            model_name='coopitem',
            name='quantity_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='coopmanager.quantityunits'),
        ),
    ]
