# Generated by Django 4.0.4 on 2022-04-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coopmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceBrackets',
            new_name='PriceBracket',
        ),
        migrations.RenameModel(
            old_name='QuantityUnits',
            new_name='QuantityUnit',
        ),
    ]
