# Generated by Django 4.0.4 on 2022-04-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coopmanager', '0002_rename_pricebrackets_pricebracket_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingBasket',
        ),
    ]
