# Generated by Django 4.0.4 on 2022-04-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopmanager', '0003_delete_shoppingbasket'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulatedCoopItemSerializer',
            fields=[
                ('coopitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coopmanager.coopitem')),
            ],
            bases=('coopmanager.coopitem',),
        ),
    ]
